// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibrjwldvyuhwcfzdmimv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlicmp3bGR2eXVod2NmemRtaW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM5NDUzMjIsImV4cCI6MjA3OTUyMTMyMn0.bCR6cHo5o_eiVeozyjPZv9tc-7v3Dj98a3lfUEUYyCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});